name: streamx
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # ---- Networking ----
  dio: ^4.0.6
  retrofit: ^3.0.1
  json_annotation: ^4.8.0

  # ---- Local Storage ----
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.11

  # ---- State Management ----
  provider: ^6.0.5

  # ---- UI & UX ----
  cached_network_image: ^3.2.3
  google_fonts: ^3.0.1
  shimmer: ^2.0.0
  flutter_svg: ^1.1.6

  # ---- Utility ----
  connectivity_plus: ^3.0.3
  share_plus: ^6.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  retrofit_generator: ^4.0.3
  json_serializable: ^6.5.4
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.2.19

flutter:
  uses-material-design: true
  assets:
    - assets/images/placeholder.jpg
    - assets/images/app_icon.jpg
    - assets/images/app_splash.png

# ✅ APP ICON CONFIG
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.jpg"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/images/app_icon.jpg"

# ✅ SPLASH SCREEN CONFIG
flutter_native_splash:
  color: "#000000"
  image: assets/images/app_splash.png
  branding: assets/images/app_icon.jpg
  android_12:
    color: "#000000"
    image: assets/images/app_splash.png
